name: test

on:
  push:
    branches: 
      -main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps: 
      -name: Checkout code
        uses: action/checkout@v3

      -name: Print hello
        runL: echo "Hello, Git action"
