name: CI/CD ReactJS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: |
          cd FE/my-app
          npm install
      
      - name: Build
        run: |
          cd FE/my-app
          npm run build
      
      - name: Done
        run: echo "✅ Build successful!"
